/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharCadastro = new javax.swing.JLabel();
        lbTxt = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        lbUser = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        botaoCad = new javax.swing.JPanel();
        botaoCadastrarUsuario = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setLayout(null);

        barraFerramentas.setBackground(new java.awt.Color(255, 51, 0));
        barraFerramentas.setForeground(new java.awt.Color(255, 255, 255));
        barraFerramentas.setPreferredSize(new java.awt.Dimension(586, 45));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tela de Cadastro");

        javax.swing.GroupLayout barraFerramentasLayout = new javax.swing.GroupLayout(barraFerramentas);
        barraFerramentas.setLayout(barraFerramentasLayout);
        barraFerramentasLayout.setHorizontalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        barraFerramentasLayout.setVerticalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraFerramentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        blocoMain.add(barraFerramentas);
        barraFerramentas.setBounds(0, 0, 534, 45);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));
        botaoFechar.setLayout(null);

        botaoFecharCadastro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharCadastro.setText("X");
        botaoFecharCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharCadastroMouseExited(evt);
            }
        });
        botaoFechar.add(botaoFecharCadastro);
        botaoFecharCadastro.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(534, 0, 38, 45);

        lbTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTxt.setForeground(new java.awt.Color(255, 255, 255));
        lbTxt.setText("Nome:");
        blocoMain.add(lbTxt);
        lbTxt.setBounds(130, 60, 70, 20);

        campoEmail.setBackground(new java.awt.Color(35, 35, 35));
        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(255, 255, 255));
        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        blocoMain.add(campoEmail);
        campoEmail.setBounds(130, 230, 340, 30);

        lbUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUser.setForeground(new java.awt.Color(255, 255, 255));
        lbUser.setText("Nome de Usuário:");
        blocoMain.add(lbUser);
        lbUser.setBounds(130, 130, 130, 20);

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail.setText("E-mail:");
        blocoMain.add(lbEmail);
        lbEmail.setBounds(130, 200, 50, 20);

        lbSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("Senha:");
        blocoMain.add(lbSenha);
        lbSenha.setBounds(130, 270, 50, 20);

        campoSenha.setBackground(new java.awt.Color(35, 35, 35));
        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(255, 255, 255));
        campoSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSenhaFocusLost(evt);
            }
        });
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        blocoMain.add(campoSenha);
        campoSenha.setBounds(130, 300, 340, 30);

        botaoCad.setBackground(new java.awt.Color(255, 51, 0));

        botaoCadastrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCadastrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoCadastrarUsuario.setText("Cadastrar");
        botaoCadastrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCadastrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCadastrarUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoCadLayout = new javax.swing.GroupLayout(botaoCad);
        botaoCad.setLayout(botaoCadLayout);
        botaoCadLayout.setHorizontalGroup(
            botaoCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botaoCadLayout.setVerticalGroup(
            botaoCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoCadastrarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        blocoMain.add(botaoCad);
        botaoCad.setBounds(240, 340, 120, 50);

        campoNome.setBackground(new java.awt.Color(35, 35, 35));
        campoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(255, 255, 255));
        campoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeFocusLost(evt);
            }
        });
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        blocoMain.add(campoNome);
        campoNome.setBounds(130, 90, 340, 30);

        campoUser.setBackground(new java.awt.Color(35, 35, 35));
        campoUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoUser.setForeground(new java.awt.Color(255, 255, 255));
        campoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUserFocusLost(evt);
            }
        });
        campoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUserActionPerformed(evt);
            }
        });
        blocoMain.add(campoUser);
        campoUser.setBounds(130, 160, 340, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blocoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blocoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(572, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharCadastroMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharCadastroMouseClicked

    private void botaoCadastrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuarioMouseClicked
        String nome, user, email;
        String senha;
        
        nome = campoNome.getText();
        user = campoUser.getText();
        email = campoEmail.getText();
        senha = String.valueOf(campoSenha.getPassword());
        
        Usuario userCriado = new Usuario(nome, user, email, senha);
        
        ForumMTP.listaUsuarios.add(userCriado);
        
        Gerenciadores.escreverArquivoUsuarios(userCriado);
        
        
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCadastrarUsuarioMouseClicked

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed

    }//GEN-LAST:event_campoEmailActionPerformed

    private void botaoFecharCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharCadastroMouseEntered
        botaoFechar.setBackground(new Color(0, 102,0));
    }//GEN-LAST:event_botaoFecharCadastroMouseEntered

    private void botaoFecharCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharCadastroMouseExited
        botaoFechar.setBackground(new Color(255,51, 0));
    }//GEN-LAST:event_botaoFecharCadastroMouseExited

    private void botaoCadastrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuarioMouseEntered
        botaoCad.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoCadastrarUsuarioMouseEntered

    private void botaoCadastrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuarioMouseExited
        botaoCad.setBackground(new Color(255,51, 0));
    }//GEN-LAST:event_botaoCadastrarUsuarioMouseExited

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
        campoEmail.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoEmailFocusGained

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        campoEmail.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoEmailFocusLost

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed

    }//GEN-LAST:event_campoSenhaActionPerformed

    private void campoNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusGained
        campoNome.setBorder(new LineBorder(new Color(255,51,0), 2));        
    }//GEN-LAST:event_campoNomeFocusGained

    private void campoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusLost
        campoNome.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoNomeFocusLost

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUserFocusGained
        campoUser.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoUserFocusGained

    private void campoUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUserFocusLost
        campoUser.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoUserFocusLost

    private void campoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUserActionPerformed

    private void campoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusGained
        campoSenha.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoSenhaFocusGained

    private void campoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusLost
        campoSenha.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoSenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoCad;
    private javax.swing.JLabel botaoCadastrarUsuario;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharCadastro;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTxt;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
}
