/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.xml.bind.annotation.XmlElement;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class ConsultarTpc extends javax.swing.JFrame {

    
    protected Usuario recall = Home.user;
    
    public void esvaziaCaixa(){
        caixaSelecaoTpc.removeAllItems();
    }
    
    /**
     * Creates new form ConsultarTpc
     */
    public ConsultarTpc() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        CriarTpc = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        campoKey = new javax.swing.JTextField();
        labelKey = new javax.swing.JLabel();
        botaoBack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botaoConsultar = new javax.swing.JPanel();
        botaoConsultarTpc = new javax.swing.JLabel();
        painelBotaoProcurar = new javax.swing.JPanel();
        botaoSearch = new javax.swing.JLabel();
        caixaSelecaoTpc = new javax.swing.JComboBox<>();
        labelEscolherTpc = new javax.swing.JLabel();
        tituloTpc = new javax.swing.JLabel();
        conteudo = new javax.swing.JLabel();
        areaConteudo = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        conte = new javax.swing.JScrollPane();
        conteudoK = new javax.swing.JTextArea();
        tituloTopicoK = new javax.swing.JLabel();
        labelResps = new javax.swing.JLabel();
        areaRespostas = new javax.swing.JScrollPane();
        areaResp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setLayout(null);

        barraFerramentas.setBackground(new java.awt.Color(255, 51, 0));
        barraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraFerramentas.setPreferredSize(new java.awt.Dimension(800, 45));

        CriarTpc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CriarTpc.setForeground(new java.awt.Color(255, 255, 255));
        CriarTpc.setText("Consultar Tópico");

        javax.swing.GroupLayout barraFerramentasLayout = new javax.swing.GroupLayout(barraFerramentas);
        barraFerramentas.setLayout(barraFerramentasLayout);
        barraFerramentasLayout.setHorizontalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CriarTpc)
                .addContainerGap(987, Short.MAX_VALUE))
        );
        barraFerramentasLayout.setVerticalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CriarTpc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blocoMain.add(barraFerramentas);
        barraFerramentas.setBounds(0, 0, 1124, 45);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));
        botaoFechar.setLayout(null);

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });
        botaoFechar.add(botaoFecharTelaP);
        botaoFecharTelaP.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(1162, 0, 38, 45);

        botaoMinimizar.setBackground(new java.awt.Color(255, 51, 0));
        botaoMinimizar.setLayout(null);

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });
        botaoMinimizar.add(botaoMinimizarTelaP);
        botaoMinimizarTelaP.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoMinimizar);
        botaoMinimizar.setBounds(1124, 0, 38, 45);

        campoKey.setBackground(new java.awt.Color(35, 35, 35));
        campoKey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoKey.setForeground(new java.awt.Color(255, 255, 255));
        campoKey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoKeyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoKeyFocusLost(evt);
            }
        });
        campoKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoKeyActionPerformed(evt);
            }
        });
        blocoMain.add(campoKey);
        campoKey.setBounds(50, 90, 250, 30);

        labelKey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKey.setForeground(new java.awt.Color(255, 255, 255));
        labelKey.setText("Digite uma palavra-chave:");
        blocoMain.add(labelKey);
        labelKey.setBounds(100, 60, 160, 20);

        botaoBack.setBackground(new java.awt.Color(255, 51, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/arrow.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoBackLayout = new javax.swing.GroupLayout(botaoBack);
        botaoBack.setLayout(botaoBackLayout);
        botaoBackLayout.setHorizontalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botaoBackLayout.setVerticalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blocoMain.add(botaoBack);
        botaoBack.setBounds(20, 480, 100, 100);

        botaoConsultar.setBackground(new java.awt.Color(255, 51, 0));
        botaoConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConsultarMouseClicked(evt);
            }
        });

        botaoConsultarTpc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoConsultarTpc.setForeground(new java.awt.Color(255, 255, 255));
        botaoConsultarTpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoConsultarTpc.setText("Consultar");
        botaoConsultarTpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConsultarTpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConsultarTpcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConsultarTpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConsultarTpcMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoConsultarLayout = new javax.swing.GroupLayout(botaoConsultar);
        botaoConsultar.setLayout(botaoConsultarLayout);
        botaoConsultarLayout.setHorizontalGroup(
            botaoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(botaoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoConsultarTpc, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        botaoConsultarLayout.setVerticalGroup(
            botaoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botaoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoConsultarTpc, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        blocoMain.add(botaoConsultar);
        botaoConsultar.setBounds(120, 130, 120, 50);

        painelBotaoProcurar.setBackground(new java.awt.Color(255, 51, 0));
        painelBotaoProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelBotaoProcurarMouseClicked(evt);
            }
        });

        botaoSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSearch.setForeground(new java.awt.Color(255, 255, 255));
        botaoSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoSearch.setText("Procurar");
        botaoSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelBotaoProcurarLayout = new javax.swing.GroupLayout(painelBotaoProcurar);
        painelBotaoProcurar.setLayout(painelBotaoProcurarLayout);
        painelBotaoProcurarLayout.setHorizontalGroup(
            painelBotaoProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        painelBotaoProcurarLayout.setVerticalGroup(
            painelBotaoProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        blocoMain.add(painelBotaoProcurar);
        painelBotaoProcurar.setBounds(1000, 90, 120, 30);

        caixaSelecaoTpc.setToolTipText("");
        caixaSelecaoTpc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caixaSelecaoTpcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caixaSelecaoTpcFocusLost(evt);
            }
        });
        caixaSelecaoTpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaSelecaoTpcMouseClicked(evt);
            }
        });
        caixaSelecaoTpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSelecaoTpcActionPerformed(evt);
            }
        });
        blocoMain.add(caixaSelecaoTpc);
        caixaSelecaoTpc.setBounds(890, 60, 290, 20);

        labelEscolherTpc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEscolherTpc.setForeground(new java.awt.Color(255, 255, 255));
        labelEscolherTpc.setText("Escolha o tópico:");
        blocoMain.add(labelEscolherTpc);
        labelEscolherTpc.setBounds(770, 60, 110, 22);

        tituloTpc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloTpc.setForeground(new java.awt.Color(255, 255, 255));
        tituloTpc.setText("Título do Tópico:");
        blocoMain.add(tituloTpc);
        tituloTpc.setBounds(360, 90, 150, 22);

        conteudo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        conteudo.setForeground(new java.awt.Color(255, 255, 255));
        conteudo.setText("Conteúdo:");
        blocoMain.add(conteudo);
        conteudo.setBounds(360, 130, 90, 22);

        areaConteudo.setBackground(new java.awt.Color(17, 17, 17));
        areaConteudo.setBorder(null);
        areaConteudo.setAutoscrolls(true);

        jPanel6.setBackground(new java.awt.Color(17, 17, 17));

        conte.setBackground(new java.awt.Color(17, 17, 17));
        conte.setBorder(null);

        conteudoK.setEditable(false);
        conteudoK.setBackground(new java.awt.Color(17, 17, 17));
        conteudoK.setColumns(20);
        conteudoK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        conteudoK.setForeground(new java.awt.Color(255, 255, 255));
        conteudoK.setLineWrap(true);
        conteudoK.setRows(5);
        conteudoK.setBorder(null);
        conteudoK.setPreferredSize(new java.awt.Dimension(740, 100));
        conte.setViewportView(conteudoK);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(conte)
                    .addGap(0, 0, 0)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(conte)
                    .addGap(0, 0, 0)))
        );

        areaConteudo.setViewportView(jPanel6);

        blocoMain.add(areaConteudo);
        areaConteudo.setBounds(310, 160, 740, 100);

        tituloTopicoK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloTopicoK.setForeground(new java.awt.Color(255, 255, 255));
        blocoMain.add(tituloTopicoK);
        tituloTopicoK.setBounds(500, 90, 320, 20);

        labelResps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelResps.setForeground(new java.awt.Color(255, 255, 255));
        labelResps.setText("Respostas:");
        blocoMain.add(labelResps);
        labelResps.setBounds(360, 300, 90, 22);

        areaRespostas.setBackground(new java.awt.Color(17, 17, 17));
        areaRespostas.setBorder(null);

        areaResp.setEditable(false);
        areaResp.setBackground(new java.awt.Color(17, 17, 17));
        areaResp.setColumns(20);
        areaResp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        areaResp.setForeground(new java.awt.Color(255, 255, 255));
        areaResp.setLineWrap(true);
        areaResp.setRows(5);
        areaResp.setBorder(null);
        areaResp.setPreferredSize(new java.awt.Dimension(740, 100));
        areaRespostas.setViewportView(areaResp);

        blocoMain.add(areaRespostas);
        areaRespostas.setBounds(310, 340, 740, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        botaoMinimizar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        botaoMinimizar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        botaoFechar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        botaoFechar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void campoKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyFocusGained
        campoKey.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoKeyFocusGained

    private void campoKeyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyFocusLost
        campoKey.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoKeyFocusLost

    private void campoKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoKeyActionPerformed
    }//GEN-LAST:event_campoKeyActionPerformed

    private void botaoConsultarTpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarTpcMouseClicked
        esvaziaCaixa();
        String keyWord = campoKey.getText();

        for(int i=0; i<ForumMTP.listaTopicos.size();i++){
           if(keyWord.equals(ForumMTP.listaTopicos.get(i).getKey1()) || keyWord.equals(ForumMTP.listaTopicos.get(i).getKey2()) || keyWord.equals(ForumMTP.listaTopicos.get(i).getKey3()) || keyWord.equals(ForumMTP.listaTopicos.get(i).getKey4()) || keyWord.equals(ForumMTP.listaTopicos.get(i).getKey5())){
             caixaSelecaoTpc.addItem(ForumMTP.listaTopicos.get(i).getTitulo());
           }
        }
    }//GEN-LAST:event_botaoConsultarTpcMouseClicked

    private void botaoConsultarTpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarTpcMouseEntered
        botaoConsultar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoConsultarTpcMouseEntered

    private void botaoConsultarTpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarTpcMouseExited
        botaoConsultar.setBackground(new Color(255, 51, 00));
    }//GEN-LAST:event_botaoConsultarTpcMouseExited

    private void botaoConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarMouseClicked

    }//GEN-LAST:event_botaoConsultarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        botaoBack.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        botaoBack.setBackground(new Color(251, 51, 0));
    }//GEN-LAST:event_jLabel4MouseExited

    private void botaoSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSearchMouseClicked
        Object nomeT = caixaSelecaoTpc.getSelectedItem();
        
        for(int i=0; i<ForumMTP.listaTopicos.size(); i++){
            if(nomeT.equals(ForumMTP.listaTopicos.get(i).getTitulo())){
                tituloTopicoK.setText(ForumMTP.listaTopicos.get(i).getTitulo());
                conteudoK.setText(ForumMTP.listaTopicos.get(i).getConteudo());
                areaResp.setText(ForumMTP.listaTopicos.get(i).retorno2());
            }
        }
        
    }//GEN-LAST:event_botaoSearchMouseClicked

    private void botaoSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSearchMouseEntered
        painelBotaoProcurar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoSearchMouseEntered

    private void botaoSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSearchMouseExited
        painelBotaoProcurar.setBackground(new Color(255, 51, 00));
    }//GEN-LAST:event_botaoSearchMouseExited

    private void painelBotaoProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBotaoProcurarMouseClicked

    }//GEN-LAST:event_painelBotaoProcurarMouseClicked

    private void caixaSelecaoTpcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecaoTpcFocusGained
    }//GEN-LAST:event_caixaSelecaoTpcFocusGained

    private void caixaSelecaoTpcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecaoTpcFocusLost
    }//GEN-LAST:event_caixaSelecaoTpcFocusLost

    private void caixaSelecaoTpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaSelecaoTpcMouseClicked

    }//GEN-LAST:event_caixaSelecaoTpcMouseClicked

    private void caixaSelecaoTpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSelecaoTpcActionPerformed

    }//GEN-LAST:event_caixaSelecaoTpcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarTpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarTpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarTpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarTpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarTpc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CriarTpc;
    private javax.swing.JScrollPane areaConteudo;
    private javax.swing.JTextArea areaResp;
    private javax.swing.JScrollPane areaRespostas;
    private javax.swing.JPanel barraFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoBack;
    private javax.swing.JPanel botaoConsultar;
    private javax.swing.JLabel botaoConsultarTpc;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JPanel botaoMinimizar;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JLabel botaoSearch;
    protected static javax.swing.JComboBox<String> caixaSelecaoTpc;
    private javax.swing.JTextField campoKey;
    private javax.swing.JScrollPane conte;
    private javax.swing.JLabel conteudo;
    private javax.swing.JTextArea conteudoK;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelEscolherTpc;
    private javax.swing.JLabel labelKey;
    private javax.swing.JLabel labelResps;
    private javax.swing.JPanel painelBotaoProcurar;
    private javax.swing.JLabel tituloTopicoK;
    private javax.swing.JLabel tituloTpc;
    // End of variables declaration//GEN-END:variables
}
