/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class ConsultarUser extends javax.swing.JFrame {

    protected Usuario recall = Home.user;
    
    /**
     * Creates new form ConsultarUser
     */
    public ConsultarUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        CriarTpc = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();
        botaoBack = new javax.swing.JPanel();
        retorno = new javax.swing.JLabel();
        campoConsultaUser = new javax.swing.JTextField();
        botaoConsultar = new javax.swing.JPanel();
        botaoConsultarUser = new javax.swing.JLabel();
        respostas = new javax.swing.JLabel();
        labelDigite = new javax.swing.JLabel();
        respInseridas = new javax.swing.JLabel();
        topicos = new javax.swing.JLabel();
        tpcsCriados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setPreferredSize(new java.awt.Dimension(800, 600));
        blocoMain.setLayout(null);

        barraFerramentas.setBackground(new java.awt.Color(255, 51, 0));
        barraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraFerramentas.setPreferredSize(new java.awt.Dimension(800, 45));

        CriarTpc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CriarTpc.setForeground(new java.awt.Color(255, 255, 255));
        CriarTpc.setText("Consultar Usuário");

        javax.swing.GroupLayout barraFerramentasLayout = new javax.swing.GroupLayout(barraFerramentas);
        barraFerramentas.setLayout(barraFerramentasLayout);
        barraFerramentasLayout.setHorizontalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CriarTpc)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        barraFerramentasLayout.setVerticalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CriarTpc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blocoMain.add(barraFerramentas);
        barraFerramentas.setBounds(0, 0, 724, 45);

        botaoMinimizar.setBackground(new java.awt.Color(255, 51, 0));
        botaoMinimizar.setLayout(null);

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });
        botaoMinimizar.add(botaoMinimizarTelaP);
        botaoMinimizarTelaP.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoMinimizar);
        botaoMinimizar.setBounds(724, 0, 38, 45);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));
        botaoFechar.setLayout(null);

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });
        botaoFechar.add(botaoFecharTelaP);
        botaoFecharTelaP.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(762, 0, 38, 45);

        botaoBack.setBackground(new java.awt.Color(255, 51, 0));

        retorno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/arrow.png"))); // NOI18N
        retorno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retornoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retornoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retornoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoBackLayout = new javax.swing.GroupLayout(botaoBack);
        botaoBack.setLayout(botaoBackLayout);
        botaoBackLayout.setHorizontalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(retorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botaoBackLayout.setVerticalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(retorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blocoMain.add(botaoBack);
        botaoBack.setBounds(20, 280, 100, 100);

        campoConsultaUser.setBackground(new java.awt.Color(35, 35, 35));
        campoConsultaUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoConsultaUser.setForeground(new java.awt.Color(255, 255, 255));
        campoConsultaUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoConsultaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConsultaUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoConsultaUserFocusLost(evt);
            }
        });
        campoConsultaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaUserActionPerformed(evt);
            }
        });
        blocoMain.add(campoConsultaUser);
        campoConsultaUser.setBounds(220, 110, 340, 30);

        botaoConsultar.setBackground(new java.awt.Color(255, 51, 0));
        botaoConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConsultarMouseClicked(evt);
            }
        });

        botaoConsultarUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoConsultarUser.setForeground(new java.awt.Color(255, 255, 255));
        botaoConsultarUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoConsultarUser.setText("Consultar");
        botaoConsultarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConsultarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConsultarUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConsultarUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConsultarUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoConsultarLayout = new javax.swing.GroupLayout(botaoConsultar);
        botaoConsultar.setLayout(botaoConsultarLayout);
        botaoConsultarLayout.setHorizontalGroup(
            botaoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoConsultarUser, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botaoConsultarLayout.setVerticalGroup(
            botaoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoConsultarUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        blocoMain.add(botaoConsultar);
        botaoConsultar.setBounds(320, 170, 120, 50);

        respostas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        respostas.setForeground(new java.awt.Color(255, 255, 255));
        blocoMain.add(respostas);
        respostas.setBounds(220, 290, 130, 20);

        labelDigite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDigite.setForeground(new java.awt.Color(255, 255, 255));
        labelDigite.setText("Digite o Nome de Usuário:");
        blocoMain.add(labelDigite);
        labelDigite.setBounds(300, 70, 160, 20);

        respInseridas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        respInseridas.setForeground(new java.awt.Color(255, 255, 255));
        respInseridas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blocoMain.add(respInseridas);
        respInseridas.setBounds(350, 290, 60, 20);

        topicos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topicos.setForeground(new java.awt.Color(255, 255, 255));
        blocoMain.add(topicos);
        topicos.setBounds(220, 260, 100, 20);

        tpcsCriados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpcsCriados.setForeground(new java.awt.Color(255, 255, 255));
        tpcsCriados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blocoMain.add(tpcsCriados);
        tpcsCriados.setBounds(350, 260, 60, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(800, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        botaoMinimizar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        botaoMinimizar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        botaoFechar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        botaoFechar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void campoConsultaUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConsultaUserFocusGained
        campoConsultaUser.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoConsultaUserFocusGained

    private void campoConsultaUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConsultaUserFocusLost
        campoConsultaUser.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoConsultaUserFocusLost

    private void campoConsultaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsultaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConsultaUserActionPerformed

    private void botaoConsultarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarUserMouseClicked
        topicos.setText("Tópicos criados:");
        respostas.setText("Respostas inseridas:");
        
        String nomeUser = campoConsultaUser.getText();
                
        try {
        Scanner scanner = new Scanner(new File("Usuarios.txt")); //lê arquivo externo
        while (scanner.hasNext()) {
            try {
                String linha = (scanner.nextLine());
                String[] vetor = linha.split(";");

                int contTpc = Integer.parseInt(vetor[4]);
                int contRes = Integer.parseInt(vetor[5]);
                Usuario a = new Usuario(vetor[0], vetor[1], vetor[2], vetor[3], contTpc, contRes);
                
                if(nomeUser.equals(vetor[1])){
                          respInseridas.setText(a.getRespostasDadas());
                          tpcsCriados.setText(a.getTpcsCriado());
                          return;
                } else if(scanner.hasNext() == false){
                    JOptionPane.showMessageDialog(null, "Usuário não encontrado");
                }
                
            }
            catch (NoSuchElementException excecaoElemento)  { //trata erro
                System.err.println("Arquivo com formato incorreto");
                scanner.close();
                System.exit(1);
                }
            
            }
        
        } catch (FileNotFoundException e) { //trata erro
        System.err.println("Arquivo não encontrado");
        }
        
    }//GEN-LAST:event_botaoConsultarUserMouseClicked

    private void botaoConsultarUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarUserMouseEntered
        botaoConsultar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoConsultarUserMouseEntered

    private void botaoConsultarUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarUserMouseExited
        botaoConsultar.setBackground(new Color(255, 51, 00));
    }//GEN-LAST:event_botaoConsultarUserMouseExited

    private void botaoConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarMouseClicked

    }//GEN-LAST:event_botaoConsultarMouseClicked

    private void retornoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retornoMouseExited
        botaoBack.setBackground(new Color(251, 51, 0));
    }//GEN-LAST:event_retornoMouseExited

    private void retornoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retornoMouseEntered
        botaoBack.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_retornoMouseEntered

    private void retornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retornoMouseClicked
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_retornoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CriarTpc;
    private javax.swing.JPanel barraFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoBack;
    private javax.swing.JPanel botaoConsultar;
    private javax.swing.JLabel botaoConsultarUser;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JPanel botaoMinimizar;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JTextField campoConsultaUser;
    private javax.swing.JLabel labelDigite;
    private javax.swing.JLabel respInseridas;
    private javax.swing.JLabel respostas;
    private javax.swing.JLabel retorno;
    private javax.swing.JLabel topicos;
    private javax.swing.JLabel tpcsCriados;
    // End of variables declaration//GEN-END:variables
}
