/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Scanner;
import static javafx.scene.paint.Color.color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class CriarTopico extends javax.swing.JFrame {

    protected Usuario recall = Home.user;
    
    /**
     * Creates new form CriarTopico
     */
    public CriarTopico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        blocoMain = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        CriarTpc = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        areaText = new javax.swing.JScrollPane();
        areaConteudo = new javax.swing.JTextArea();
        labelText = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        botaoCriar = new javax.swing.JPanel();
        botaoCriarTopico = new javax.swing.JLabel();
        botaoBack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();
        campoKeyword1 = new javax.swing.JTextField();
        labelPalavras = new javax.swing.JLabel();
        campoKeyword2 = new javax.swing.JTextField();
        campoKeyword3 = new javax.swing.JTextField();
        campoKeyword4 = new javax.swing.JTextField();
        campoKeyword5 = new javax.swing.JTextField();

        jTextField5.setBackground(new java.awt.Color(35, 35, 35));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setToolTipText("");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(35, 35, 35));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setToolTipText("");
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(35, 35, 35));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setToolTipText("");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setBackground(new java.awt.Color(35, 35, 35));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setToolTipText("");
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setPreferredSize(new java.awt.Dimension(800, 600));
        blocoMain.setLayout(null);

        barraFerramentas.setBackground(new java.awt.Color(255, 51, 0));
        barraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraFerramentas.setPreferredSize(new java.awt.Dimension(800, 45));

        CriarTpc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CriarTpc.setForeground(new java.awt.Color(255, 255, 255));
        CriarTpc.setText("Criar Tópico");

        javax.swing.GroupLayout barraFerramentasLayout = new javax.swing.GroupLayout(barraFerramentas);
        barraFerramentas.setLayout(barraFerramentasLayout);
        barraFerramentasLayout.setHorizontalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CriarTpc)
                .addContainerGap(624, Short.MAX_VALUE))
        );
        barraFerramentasLayout.setVerticalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CriarTpc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blocoMain.add(barraFerramentas);
        barraFerramentas.setBounds(0, 0, 724, 45);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Título do Tópico:");
        blocoMain.add(labelTitulo);
        labelTitulo.setBounds(240, 50, 160, 20);

        areaConteudo.setBackground(new java.awt.Color(35, 35, 35));
        areaConteudo.setColumns(20);
        areaConteudo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        areaConteudo.setForeground(new java.awt.Color(255, 255, 255));
        areaConteudo.setRows(5);
        areaConteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        areaConteudo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaConteudoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaConteudoFocusLost(evt);
            }
        });
        areaText.setViewportView(areaConteudo);

        blocoMain.add(areaText);
        areaText.setBounds(240, 150, 340, 230);

        labelText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelText.setForeground(new java.awt.Color(255, 255, 255));
        labelText.setText("Texto do tópico:");
        blocoMain.add(labelText);
        labelText.setBounds(240, 120, 160, 20);

        campoTitulo.setBackground(new java.awt.Color(35, 35, 35));
        campoTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        campoTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTituloFocusLost(evt);
            }
        });
        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });
        blocoMain.add(campoTitulo);
        campoTitulo.setBounds(240, 80, 340, 30);

        botaoCriar.setBackground(new java.awt.Color(255, 51, 0));
        botaoCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCriarMouseClicked(evt);
            }
        });

        botaoCriarTopico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCriarTopico.setForeground(new java.awt.Color(255, 255, 255));
        botaoCriarTopico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoCriarTopico.setText("Criar Tópico");
        botaoCriarTopico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCriarTopico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCriarTopicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCriarTopicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCriarTopicoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoCriarLayout = new javax.swing.GroupLayout(botaoCriar);
        botaoCriar.setLayout(botaoCriarLayout);
        botaoCriarLayout.setHorizontalGroup(
            botaoCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoCriarTopico, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botaoCriarLayout.setVerticalGroup(
            botaoCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoCriarTopico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        blocoMain.add(botaoCriar);
        botaoCriar.setBounds(340, 520, 120, 50);

        botaoBack.setBackground(new java.awt.Color(255, 51, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/arrow.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoBackLayout = new javax.swing.GroupLayout(botaoBack);
        botaoBack.setLayout(botaoBackLayout);
        botaoBackLayout.setHorizontalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botaoBackLayout.setVerticalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blocoMain.add(botaoBack);
        botaoBack.setBounds(20, 480, 100, 100);

        botaoMinimizar.setBackground(new java.awt.Color(255, 51, 0));
        botaoMinimizar.setLayout(null);

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });
        botaoMinimizar.add(botaoMinimizarTelaP);
        botaoMinimizarTelaP.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoMinimizar);
        botaoMinimizar.setBounds(724, 0, 38, 45);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));
        botaoFechar.setLayout(null);

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });
        botaoFechar.add(botaoFecharTelaP);
        botaoFecharTelaP.setBounds(0, 0, 38, 45);

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(762, 0, 38, 45);

        campoKeyword1.setBackground(new java.awt.Color(35, 35, 35));
        campoKeyword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoKeyword1.setForeground(new java.awt.Color(255, 255, 255));
        campoKeyword1.setToolTipText("");
        campoKeyword1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoKeyword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoKeyword1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoKeyword1FocusLost(evt);
            }
        });
        campoKeyword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoKeyword1ActionPerformed(evt);
            }
        });
        blocoMain.add(campoKeyword1);
        campoKeyword1.setBounds(260, 420, 80, 30);

        labelPalavras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPalavras.setForeground(new java.awt.Color(255, 255, 255));
        labelPalavras.setText("Palavras-chave:");
        blocoMain.add(labelPalavras);
        labelPalavras.setBounds(240, 390, 160, 20);

        campoKeyword2.setBackground(new java.awt.Color(35, 35, 35));
        campoKeyword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoKeyword2.setForeground(new java.awt.Color(255, 255, 255));
        campoKeyword2.setToolTipText("");
        campoKeyword2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoKeyword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoKeyword2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoKeyword2FocusLost(evt);
            }
        });
        campoKeyword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoKeyword2ActionPerformed(evt);
            }
        });
        blocoMain.add(campoKeyword2);
        campoKeyword2.setBounds(350, 420, 80, 30);

        campoKeyword3.setBackground(new java.awt.Color(35, 35, 35));
        campoKeyword3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoKeyword3.setForeground(new java.awt.Color(255, 255, 255));
        campoKeyword3.setToolTipText("");
        campoKeyword3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoKeyword3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoKeyword3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoKeyword3FocusLost(evt);
            }
        });
        campoKeyword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoKeyword3ActionPerformed(evt);
            }
        });
        blocoMain.add(campoKeyword3);
        campoKeyword3.setBounds(440, 420, 80, 30);

        campoKeyword4.setBackground(new java.awt.Color(35, 35, 35));
        campoKeyword4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoKeyword4.setForeground(new java.awt.Color(255, 255, 255));
        campoKeyword4.setToolTipText("");
        campoKeyword4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoKeyword4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoKeyword4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoKeyword4FocusLost(evt);
            }
        });
        campoKeyword4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoKeyword4ActionPerformed(evt);
            }
        });
        blocoMain.add(campoKeyword4);
        campoKeyword4.setBounds(310, 460, 80, 30);

        campoKeyword5.setBackground(new java.awt.Color(35, 35, 35));
        campoKeyword5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoKeyword5.setForeground(new java.awt.Color(255, 255, 255));
        campoKeyword5.setToolTipText("");
        campoKeyword5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoKeyword5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoKeyword5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoKeyword5FocusLost(evt);
            }
        });
        campoKeyword5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoKeyword5ActionPerformed(evt);
            }
        });
        blocoMain.add(campoKeyword5);
        campoKeyword5.setBounds(400, 460, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void botaoCriarTopicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCriarTopicoMouseClicked
        String titulo, conteudo, key1, key2, key3, key4, key5;
        
        titulo = campoTitulo.getText();
        conteudo = areaConteudo.getText();
        key1 = campoKeyword1.getText();
        key2 = campoKeyword2.getText();
        key3 = campoKeyword3.getText();
        key4 = campoKeyword4.getText();
        key5 = campoKeyword5.getText();
        
        Topico topicoCriado = new Topico(titulo, conteudo, key1, key2, key3, key4, key5);
        
        ForumMTP.listaTopicos.add(topicoCriado);
        
        Gerenciadores.escreverArquivoTopicos(topicoCriado);
        
        recall.ContadorTpc();
        
        for(int i = 0; i<ForumMTP.listaUsuarios.size(); i++){
            if(ForumMTP.listaUsuarios.get(i).getUser().equals(recall.getUser())){
                Gerenciadores.RemovedorUser(ForumMTP.listaUsuarios.get(i));
            }
        }
        
        ForumMTP.listaUsuarios.add(recall);
        
        for(int i = 0; i<ForumMTP.listaUsuarios.size(); i++)
        System.out.println(ForumMTP.listaUsuarios.get(i));
        
        System.out.println("");
        
        Gerenciadores.escreverArquivoUsuariosFalse(recall);
        
        for(int i = 0 ; i<ForumMTP.listaUsuarios.size(); i++){
            if(!ForumMTP.listaUsuarios.get(i).getUser().equals(recall.getUser())){
                Gerenciadores.escreverArquivoUsuarios(ForumMTP.listaUsuarios.get(i));
         }
        }
        
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_botaoCriarTopicoMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        botaoBack.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        botaoBack.setBackground(new Color(251, 51, 0));
    }//GEN-LAST:event_jLabel4MouseExited

    private void botaoCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCriarMouseClicked
        
    }//GEN-LAST:event_botaoCriarMouseClicked

    private void botaoCriarTopicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCriarTopicoMouseEntered
        botaoCriar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoCriarTopicoMouseEntered

    private void botaoCriarTopicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCriarTopicoMouseExited
        botaoCriar.setBackground(new Color(255, 51, 00));
    }//GEN-LAST:event_botaoCriarTopicoMouseExited

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        botaoFechar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        botaoFechar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        botaoMinimizar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        botaoMinimizar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void campoTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTituloFocusGained
        campoTitulo.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoTituloFocusGained

    private void campoTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTituloFocusLost
        campoTitulo.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoTituloFocusLost

    private void areaConteudoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaConteudoFocusGained
        areaConteudo.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_areaConteudoFocusGained

    private void areaConteudoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaConteudoFocusLost
        areaConteudo.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_areaConteudoFocusLost

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        jTextField7.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_jTextField7FocusGained

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        jTextField7.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        jTextField8.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        jTextField8.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        jTextField9.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusGained
        jTextField9.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_jTextField9FocusGained

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        jTextField5.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        jTextField5.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_jTextField5FocusGained

    private void campoKeyword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoKeyword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoKeyword1ActionPerformed

    private void campoKeyword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword1FocusLost
        campoKeyword1.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoKeyword1FocusLost

    private void campoKeyword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword1FocusGained
        campoKeyword1.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoKeyword1FocusGained

    private void campoKeyword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword2FocusGained
        campoKeyword2.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoKeyword2FocusGained

    private void campoKeyword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword2FocusLost
        campoKeyword2.setBorder(new LineBorder(new Color(88,88,88), 2));

    }//GEN-LAST:event_campoKeyword2FocusLost

    private void campoKeyword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoKeyword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoKeyword2ActionPerformed

    private void campoKeyword3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword3FocusGained
        campoKeyword3.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoKeyword3FocusGained

    private void campoKeyword3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword3FocusLost
        campoKeyword3.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoKeyword3FocusLost

    private void campoKeyword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoKeyword3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoKeyword3ActionPerformed

    private void campoKeyword4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword4FocusGained
        campoKeyword4.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoKeyword4FocusGained

    private void campoKeyword4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword4FocusLost
        campoKeyword4.setBorder(new LineBorder(new Color(88,88,88), 2));

    }//GEN-LAST:event_campoKeyword4FocusLost

    private void campoKeyword4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoKeyword4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoKeyword4ActionPerformed

    private void campoKeyword5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword5FocusGained
        campoKeyword5.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoKeyword5FocusGained

    private void campoKeyword5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoKeyword5FocusLost
        campoKeyword5.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoKeyword5FocusLost

    private void campoKeyword5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoKeyword5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoKeyword5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarTopico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CriarTpc;
    private javax.swing.JTextArea areaConteudo;
    private javax.swing.JScrollPane areaText;
    private javax.swing.JPanel barraFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoBack;
    private javax.swing.JPanel botaoCriar;
    private javax.swing.JLabel botaoCriarTopico;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JPanel botaoMinimizar;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JTextField campoKeyword1;
    private javax.swing.JTextField campoKeyword2;
    private javax.swing.JTextField campoKeyword3;
    private javax.swing.JTextField campoKeyword4;
    private javax.swing.JTextField campoKeyword5;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel labelPalavras;
    private javax.swing.JLabel labelText;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
