/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class Home extends javax.swing.JFrame {
    
    private Color corAnterior;
    protected static Usuario user;
    protected static ArrayList <Topico> listaTopic = ForumMTP.listaTopicos;
    
    public static void mudaTexto(String texto){
        userN.setText(texto);
    }
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        barraDeFerramentas = new javax.swing.JPanel();
        telaPrincipal = new javax.swing.JLabel();
        painelCriarTPC = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        painelVisualizarTPC = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        painelConsultarUser = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        painelConsultarTPC = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelSobreProjeto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userN = new javax.swing.JLabel();
        userIco = new javax.swing.JLabel();
        userAreaIco = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setPreferredSize(new java.awt.Dimension(1200, 600));
        blocoMain.setLayout(null);

        barraDeFerramentas.setBackground(new java.awt.Color(255, 51, 0));
        barraDeFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        telaPrincipal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        telaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        telaPrincipal.setText("Tela Principal");

        javax.swing.GroupLayout barraDeFerramentasLayout = new javax.swing.GroupLayout(barraDeFerramentas);
        barraDeFerramentas.setLayout(barraDeFerramentasLayout);
        barraDeFerramentasLayout.setHorizontalGroup(
            barraDeFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(1014, Short.MAX_VALUE))
        );
        barraDeFerramentasLayout.setVerticalGroup(
            barraDeFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blocoMain.add(barraDeFerramentas);
        barraDeFerramentas.setBounds(0, 0, 1124, 45);

        painelCriarTPC.setBackground(new java.awt.Color(255, 51, 0));
        painelCriarTPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelCriarTPC.setMinimumSize(new java.awt.Dimension(220, 180));
        painelCriarTPC.setPreferredSize(new java.awt.Dimension(220, 180));
        painelCriarTPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCriarTPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelCriarTPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelCriarTPCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelCriarTPCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCriarTPCMouseReleased(evt);
            }
        });
        painelCriarTPC.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Criar Tópico");
        painelCriarTPC.add(jLabel3);
        jLabel3.setBounds(0, 11, 270, 27);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\elton\\Downloads\\Estudos\\Faculdade\\2º Período\\MTP\\Trabalhos\\Fórum\\mais.png")); // NOI18N
        painelCriarTPC.add(jLabel8);
        jLabel8.setBounds(0, 50, 270, 174);

        blocoMain.add(painelCriarTPC);
        painelCriarTPC.setBounds(310, 120, 270, 220);

        painelVisualizarTPC.setBackground(new java.awt.Color(255, 51, 0));
        painelVisualizarTPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelVisualizarTPC.setMinimumSize(new java.awt.Dimension(220, 180));
        painelVisualizarTPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelVisualizarTPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelVisualizarTPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelVisualizarTPCMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Visualizar Tópico");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/vertopcs.png"))); // NOI18N

        javax.swing.GroupLayout painelVisualizarTPCLayout = new javax.swing.GroupLayout(painelVisualizarTPC);
        painelVisualizarTPC.setLayout(painelVisualizarTPCLayout);
        painelVisualizarTPCLayout.setHorizontalGroup(
            painelVisualizarTPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelVisualizarTPCLayout.setVerticalGroup(
            painelVisualizarTPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVisualizarTPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        blocoMain.add(painelVisualizarTPC);
        painelVisualizarTPC.setBounds(610, 120, 270, 220);

        painelConsultarUser.setBackground(new java.awt.Color(255, 51, 0));
        painelConsultarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelConsultarUser.setMinimumSize(new java.awt.Dimension(220, 180));
        painelConsultarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelConsultarUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelConsultarUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelConsultarUserMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consultar Usuário");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/lupap.png"))); // NOI18N

        javax.swing.GroupLayout painelConsultarUserLayout = new javax.swing.GroupLayout(painelConsultarUser);
        painelConsultarUser.setLayout(painelConsultarUserLayout);
        painelConsultarUserLayout.setHorizontalGroup(
            painelConsultarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultarUserLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelConsultarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelConsultarUserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelConsultarUserLayout.setVerticalGroup(
            painelConsultarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultarUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(painelConsultarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultarUserLayout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(10, 10, 10)))
        );

        blocoMain.add(painelConsultarUser);
        painelConsultarUser.setBounds(160, 370, 270, 220);

        painelConsultarTPC.setBackground(new java.awt.Color(255, 51, 0));
        painelConsultarTPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelConsultarTPC.setMinimumSize(new java.awt.Dimension(220, 180));
        painelConsultarTPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelConsultarTPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelConsultarTPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelConsultarTPCMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consultar Tópico");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/consultartopico cópia.png"))); // NOI18N

        javax.swing.GroupLayout painelConsultarTPCLayout = new javax.swing.GroupLayout(painelConsultarTPC);
        painelConsultarTPC.setLayout(painelConsultarTPCLayout);
        painelConsultarTPCLayout.setHorizontalGroup(
            painelConsultarTPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelConsultarTPCLayout.setVerticalGroup(
            painelConsultarTPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultarTPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        blocoMain.add(painelConsultarTPC);
        painelConsultarTPC.setBounds(460, 370, 270, 220);

        painelSobreProjeto.setBackground(new java.awt.Color(255, 51, 0));
        painelSobreProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelSobreProjeto.setMinimumSize(new java.awt.Dimension(220, 180));
        painelSobreProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelSobreProjetoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelSobreProjetoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelSobreProjetoMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sobre o Projeto");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/sobrenos.png"))); // NOI18N

        javax.swing.GroupLayout painelSobreProjetoLayout = new javax.swing.GroupLayout(painelSobreProjeto);
        painelSobreProjeto.setLayout(painelSobreProjetoLayout);
        painelSobreProjetoLayout.setHorizontalGroup(
            painelSobreProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelSobreProjetoLayout.setVerticalGroup(
            painelSobreProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSobreProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        blocoMain.add(painelSobreProjeto);
        painelSobreProjeto.setBounds(760, 370, 270, 220);

        userN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userN.setForeground(new java.awt.Color(255, 255, 255));
        userN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userN.setText("Username");
        userN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNMouseClicked(evt);
            }
        });
        blocoMain.add(userN);
        userN.setBounds(100, 73, 110, 30);

        userIco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/bonecobranco.png"))); // NOI18N
        userIco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIcoMouseClicked(evt);
            }
        });
        blocoMain.add(userIco);
        userIco.setBounds(38, 60, 50, 50);

        userAreaIco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userAreaIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/barrauser.png"))); // NOI18N
        userAreaIco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userAreaIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userAreaIcoMouseClicked(evt);
            }
        });
        blocoMain.add(userAreaIco);
        userAreaIco.setBounds(30, 55, 186, 68);

        botaoMinimizar.setBackground(new java.awt.Color(255, 51, 0));

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoMinimizarLayout = new javax.swing.GroupLayout(botaoMinimizar);
        botaoMinimizar.setLayout(botaoMinimizarLayout);
        botaoMinimizarLayout.setHorizontalGroup(
            botaoMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botaoMinimizarLayout.setVerticalGroup(
            botaoMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        blocoMain.add(botaoMinimizar);
        botaoMinimizar.setBounds(1124, 0, 38, 45);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoFecharLayout = new javax.swing.GroupLayout(botaoFechar);
        botaoFechar.setLayout(botaoFecharLayout);
        botaoFecharLayout.setHorizontalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoFecharLayout.createSequentialGroup()
                .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoFecharLayout.setVerticalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(1162, 0, 38, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void painelCriarTPCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCriarTPCMousePressed
 
    }//GEN-LAST:event_painelCriarTPCMousePressed

    private void painelCriarTPCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCriarTPCMouseReleased
        
    }//GEN-LAST:event_painelCriarTPCMouseReleased

    private void painelCriarTPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCriarTPCMouseEntered
        corAnterior = painelCriarTPC.getBackground();
        painelCriarTPC.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_painelCriarTPCMouseEntered

    private void painelCriarTPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCriarTPCMouseExited
        painelCriarTPC.setBackground(corAnterior);
    }//GEN-LAST:event_painelCriarTPCMouseExited

    private void painelConsultarUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConsultarUserMouseEntered
        corAnterior = painelCriarTPC.getBackground();
        painelConsultarUser.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_painelConsultarUserMouseEntered

    private void painelConsultarUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConsultarUserMouseExited
        painelConsultarUser.setBackground(corAnterior);
    }//GEN-LAST:event_painelConsultarUserMouseExited

    private void painelVisualizarTPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelVisualizarTPCMouseEntered
        corAnterior = painelCriarTPC.getBackground();
        painelVisualizarTPC.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_painelVisualizarTPCMouseEntered

    private void painelVisualizarTPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelVisualizarTPCMouseExited
        painelVisualizarTPC.setBackground(corAnterior);
    }//GEN-LAST:event_painelVisualizarTPCMouseExited

    private void painelConsultarTPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConsultarTPCMouseEntered
        corAnterior = painelCriarTPC.getBackground();
        painelConsultarTPC.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_painelConsultarTPCMouseEntered

    private void painelConsultarTPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConsultarTPCMouseExited
        painelConsultarTPC.setBackground(corAnterior);
    }//GEN-LAST:event_painelConsultarTPCMouseExited

    private void painelSobreProjetoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelSobreProjetoMouseEntered
        corAnterior = painelCriarTPC.getBackground();
        painelSobreProjeto.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_painelSobreProjetoMouseEntered

    private void painelSobreProjetoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelSobreProjetoMouseExited
        painelSobreProjeto.setBackground(corAnterior);
    }//GEN-LAST:event_painelSobreProjetoMouseExited

    private void painelCriarTPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCriarTPCMouseClicked
        new CriarTopico().setVisible(true);
        dispose();
    }//GEN-LAST:event_painelCriarTPCMouseClicked

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        botaoFechar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        botaoFechar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        botaoMinimizar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        botaoMinimizar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void painelConsultarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConsultarUserMouseClicked
        new ConsultarUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_painelConsultarUserMouseClicked

    private void painelConsultarTPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConsultarTPCMouseClicked
        new ConsultarTpc().setVisible(true);
        dispose();
    }//GEN-LAST:event_painelConsultarTPCMouseClicked

    private void painelVisualizarTPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelVisualizarTPCMouseClicked
              
        System.out.println("");
        
        for(int i = 0; i<listaTopic.size(); i++)
        System.out.println(listaTopic.get(i));
        
        new VisualizarTopico().setVisible(true);
        dispose();
    }//GEN-LAST:event_painelVisualizarTPCMouseClicked

    private void userNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNMouseClicked
        new TelaSair().setVisible(true);
    }//GEN-LAST:event_userNMouseClicked

    private void userIcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIcoMouseClicked
        new TelaSair().setVisible(true);
    }//GEN-LAST:event_userIcoMouseClicked

    private void userAreaIcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAreaIcoMouseClicked
        new TelaSair().setVisible(true);
    }//GEN-LAST:event_userAreaIcoMouseClicked

    private void painelSobreProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelSobreProjetoMouseClicked
        new SobreProjeto().setVisible(true);
        dispose();
    }//GEN-LAST:event_painelSobreProjetoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraDeFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JPanel botaoMinimizar;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel painelConsultarTPC;
    private javax.swing.JPanel painelConsultarUser;
    private javax.swing.JPanel painelCriarTPC;
    private javax.swing.JPanel painelSobreProjeto;
    private javax.swing.JPanel painelVisualizarTPC;
    private javax.swing.JLabel telaPrincipal;
    private javax.swing.JLabel userAreaIco;
    private javax.swing.JLabel userIco;
    private static javax.swing.JLabel userN;
    // End of variables declaration//GEN-END:variables
}
