/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import static javafx.scene.paint.Color.color;
import java.awt.Color;
import javax.swing.border.LineBorder;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JOptionPane;


/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public void validador(){
        String user = campoLogin.getText();
        String senha = String.valueOf(campoSenha.getPassword());
        try {
        Scanner scanner = new Scanner(new File("Usuarios.txt")); //lê arquivo externo
        while (scanner.hasNext()) {
            try {
                String linha = (scanner.nextLine());
                String[] vetor = linha.split(";");
                
                int contTpc = Integer.parseInt(vetor[4]);
                int contRes = Integer.parseInt(vetor[5]);
                
                Usuario a = new Usuario(vetor[0], vetor[1], vetor[2], vetor[3], contTpc, contRes);
                
                if(senha.equals(vetor[3]) && user.equals(vetor[1])){
                    new Home().setVisible(true);
                    Home.mudaTexto(vetor[1]);
                    Home.user = a;
                    dispose();
                    return;
                } else if(scanner.hasNext() == false){
                    JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!");
                }
                
            }
            catch (NoSuchElementException excecaoElemento)  { //trata erro
                System.err.println("Arquivo com formato incorreto");
                scanner.close();
                System.exit(1);
                }
            
            }
        
        } catch (FileNotFoundException e) { //trata erro
        System.err.println("Arquivo não encontrado");
        }
    }
    
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        painelIco = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharLogin = new javax.swing.JLabel();
        labelDiscuss = new javax.swing.JLabel();
        labelBemVindo = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        botaoLogin = new javax.swing.JPanel();
        botaoEntrar = new javax.swing.JLabel();
        linkCadastrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setLayout(null);

        painelIco.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/user.png"))); // NOI18N

        javax.swing.GroupLayout painelIcoLayout = new javax.swing.GroupLayout(painelIco);
        painelIco.setLayout(painelIcoLayout);
        painelIcoLayout.setHorizontalGroup(
            painelIcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIcoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        painelIcoLayout.setVerticalGroup(
            painelIcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIcoLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        blocoMain.add(painelIco);
        painelIco.setBounds(0, 0, 454, 561);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));

        botaoFecharLogin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharLogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharLogin.setText("X");
        botaoFecharLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoFecharLayout = new javax.swing.GroupLayout(botaoFechar);
        botaoFechar.setLayout(botaoFecharLayout);
        botaoFecharLayout.setHorizontalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoFecharLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        botaoFecharLayout.setVerticalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoFecharLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(846, 0, 38, 45);

        labelDiscuss.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        labelDiscuss.setForeground(new java.awt.Color(255, 255, 255));
        labelDiscuss.setText("Fórum DiscussNation");
        labelDiscuss.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        blocoMain.add(labelDiscuss);
        labelDiscuss.setBounds(510, 60, 330, 30);

        labelBemVindo.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        labelBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        labelBemVindo.setText("Seja Bem-Vindo ao");
        labelBemVindo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        blocoMain.add(labelBemVindo);
        labelBemVindo.setBounds(530, 30, 310, 50);

        campoLogin.setBackground(new java.awt.Color(35, 35, 35));
        campoLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoLogin.setForeground(new java.awt.Color(255, 255, 255));
        campoLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoLoginFocusLost(evt);
            }
        });
        campoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campoLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                campoLoginMouseReleased(evt);
            }
        });
        campoLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoLoginKeyPressed(evt);
            }
        });
        blocoMain.add(campoLogin);
        campoLogin.setBounds(500, 180, 340, 30);

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setText("Nome de Usuário:");
        blocoMain.add(labelUser);
        labelUser.setBounds(500, 150, 120, 30);

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha:");
        blocoMain.add(labelSenha);
        labelSenha.setBounds(500, 220, 120, 30);

        campoSenha.setBackground(new java.awt.Color(35, 35, 35));
        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(255, 255, 255));
        campoSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        campoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSenhaFocusLost(evt);
            }
        });
        blocoMain.add(campoSenha);
        campoSenha.setBounds(500, 250, 340, 30);

        botaoLogin.setBackground(new java.awt.Color(255, 51, 0));

        botaoEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoEntrar.setText("Entrar");
        botaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoLoginLayout = new javax.swing.GroupLayout(botaoLogin);
        botaoLogin.setLayout(botaoLoginLayout);
        botaoLoginLayout.setHorizontalGroup(
            botaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botaoLoginLayout.setVerticalGroup(
            botaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        blocoMain.add(botaoLogin);
        botaoLogin.setBounds(610, 300, 120, 50);

        linkCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        linkCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkCadastrar.setText("Ainda não está registrado? Cadastre-se agora clicando aqui!");
        linkCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkCadastrarMouseClicked(evt);
            }
        });
        blocoMain.add(linkCadastrar);
        linkCadastrar.setBounds(500, 360, 350, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blocoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blocoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(884, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharLoginMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharLoginMouseClicked

    private void linkCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCadastrarMouseClicked
        new Cadastro().setVisible(true);
        dispose();
    }//GEN-LAST:event_linkCadastrarMouseClicked

    private void botaoEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseClicked
        validador();
       
    }//GEN-LAST:event_botaoEntrarMouseClicked

    private void botaoEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseEntered
        botaoLogin.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoEntrarMouseEntered

    private void botaoEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseExited
        botaoLogin.setBackground(new Color(255, 51, 0));
    }//GEN-LAST:event_botaoEntrarMouseExited

    private void botaoFecharLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharLoginMouseEntered
        botaoFechar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoFecharLoginMouseEntered

    private void botaoFecharLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharLoginMouseExited
        botaoFechar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharLoginMouseExited

    private void campoLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoLoginMouseEntered
    }//GEN-LAST:event_campoLoginMouseEntered

    private void campoLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoLoginMouseExited
    }//GEN-LAST:event_campoLoginMouseExited

    private void campoLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoLoginMousePressed
        
    }//GEN-LAST:event_campoLoginMousePressed

    private void campoLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusGained
        campoLogin.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoLoginFocusGained

    private void campoLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoLoginMouseReleased

    }//GEN-LAST:event_campoLoginMouseReleased

    private void campoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoLoginMouseClicked

    }//GEN-LAST:event_campoLoginMouseClicked

    private void campoLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoLoginKeyPressed
        
    }//GEN-LAST:event_campoLoginKeyPressed

    private void campoLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusLost
        campoLogin.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoLoginFocusLost

    private void campoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusGained
        campoSenha.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_campoSenhaFocusGained

    private void campoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusLost
        campoSenha.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_campoSenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blocoMain;
    private javax.swing.JLabel botaoEntrar;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharLogin;
    private javax.swing.JPanel botaoLogin;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBemVindo;
    private javax.swing.JLabel labelDiscuss;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel linkCadastrar;
    private javax.swing.JPanel painelIco;
    // End of variables declaration//GEN-END:variables
}
