/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class SobreProjeto extends javax.swing.JFrame {

    protected Usuario recall = Home.user;
    
    /**
     * Creates new form SobreProjeto
     */
    public SobreProjeto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        telaPrincipal = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();
        labelDesenvolvedores = new javax.swing.JLabel();
        labelDevs = new javax.swing.JLabel();
        areaTextoMensagem = new javax.swing.JScrollPane();
        areaTextoSobre = new javax.swing.JTextArea();
        botaoBack = new javax.swing.JPanel();
        botaoBk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setLayout(null);

        barraFerramentas.setBackground(new java.awt.Color(255, 51, 0));
        barraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        telaPrincipal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        telaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        telaPrincipal.setText("Sobre o Projeto");

        javax.swing.GroupLayout barraFerramentasLayout = new javax.swing.GroupLayout(barraFerramentas);
        barraFerramentas.setLayout(barraFerramentasLayout);
        barraFerramentasLayout.setHorizontalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        barraFerramentasLayout.setVerticalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blocoMain.add(barraFerramentas);
        barraFerramentas.setBounds(0, 0, 574, 45);

        botaoMinimizar.setBackground(new java.awt.Color(255, 51, 0));

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoMinimizarLayout = new javax.swing.GroupLayout(botaoMinimizar);
        botaoMinimizar.setLayout(botaoMinimizarLayout);
        botaoMinimizarLayout.setHorizontalGroup(
            botaoMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botaoMinimizarLayout.setVerticalGroup(
            botaoMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        blocoMain.add(botaoMinimizar);
        botaoMinimizar.setBounds(574, 0, 38, 45);

        botaoFechar.setBackground(new java.awt.Color(255, 51, 0));

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoFecharLayout = new javax.swing.GroupLayout(botaoFechar);
        botaoFechar.setLayout(botaoFecharLayout);
        botaoFecharLayout.setHorizontalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoFecharLayout.createSequentialGroup()
                .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoFecharLayout.setVerticalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(612, 0, 38, 45);

        labelDesenvolvedores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDesenvolvedores.setForeground(new java.awt.Color(255, 255, 255));
        labelDesenvolvedores.setText("Elton Soares & Sávio Ventura");
        blocoMain.add(labelDesenvolvedores);
        labelDesenvolvedores.setBounds(320, 370, 320, 70);

        labelDevs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDevs.setForeground(new java.awt.Color(255, 255, 255));
        labelDevs.setText("Developers:");
        blocoMain.add(labelDevs);
        labelDevs.setBounds(180, 380, 130, 50);

        areaTextoMensagem.setBackground(new java.awt.Color(17, 17, 17));
        areaTextoMensagem.setBorder(null);

        areaTextoSobre.setEditable(false);
        areaTextoSobre.setBackground(new java.awt.Color(17, 17, 17));
        areaTextoSobre.setColumns(20);
        areaTextoSobre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        areaTextoSobre.setForeground(new java.awt.Color(255, 255, 255));
        areaTextoSobre.setLineWrap(true);
        areaTextoSobre.setRows(5);
        areaTextoSobre.setText("Este projeto tem por finalidade a implementação, em java, de um fórum de discussões. O tema \ndeste fórum é acadêmico. Ou seja, os tópicos \nencontrados aqui serão relacionados a perguntas diversas sobre assuntos de caráter acadêmico.");
        areaTextoMensagem.setViewportView(areaTextoSobre);

        blocoMain.add(areaTextoMensagem);
        areaTextoMensagem.setBounds(120, 140, 400, 120);

        botaoBack.setBackground(new java.awt.Color(255, 51, 0));

        botaoBk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/arrow.png"))); // NOI18N
        botaoBk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoBk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoBkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoBkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoBackLayout = new javax.swing.GroupLayout(botaoBack);
        botaoBack.setLayout(botaoBackLayout);
        botaoBackLayout.setHorizontalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botaoBackLayout.setVerticalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blocoMain.add(botaoBack);
        botaoBack.setBounds(10, 340, 100, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(650, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        botaoMinimizar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        botaoMinimizar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        botaoFechar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        botaoFechar.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void botaoBkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBkMouseClicked
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_botaoBkMouseClicked

    private void botaoBkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBkMouseEntered
        botaoBack.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoBkMouseEntered

    private void botaoBkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBkMouseExited
        botaoBack.setBackground(new Color(251, 51, 0));
    }//GEN-LAST:event_botaoBkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SobreProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SobreProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SobreProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SobreProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SobreProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane areaTextoMensagem;
    private javax.swing.JTextArea areaTextoSobre;
    private javax.swing.JPanel barraFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoBack;
    private javax.swing.JLabel botaoBk;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JPanel botaoMinimizar;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JLabel labelDesenvolvedores;
    private javax.swing.JLabel labelDevs;
    private javax.swing.JLabel telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
