/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * AUTORES: ELTON SOARES & SÁVIO VENTURA
 */
public class TelaSair extends javax.swing.JFrame {

    /**
     * Creates new form TelaSair
     */
    public TelaSair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocoMain = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        telaPrincipal = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();
        labelAsk = new javax.swing.JLabel();
        painelSim = new javax.swing.JPanel();
        sim = new javax.swing.JLabel();
        painelNao = new javax.swing.JPanel();
        nao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        blocoMain.setBackground(new java.awt.Color(17, 17, 17));
        blocoMain.setLayout(null);

        barraFerramentas.setBackground(new java.awt.Color(210, 6, 7));
        barraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        telaPrincipal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        telaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        telaPrincipal.setText("Logout");

        javax.swing.GroupLayout barraFerramentasLayout = new javax.swing.GroupLayout(barraFerramentas);
        barraFerramentas.setLayout(barraFerramentasLayout);
        barraFerramentasLayout.setHorizontalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        barraFerramentasLayout.setVerticalGroup(
            barraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blocoMain.add(barraFerramentas);
        barraFerramentas.setBounds(0, 0, 424, 45);

        botaoMinimizar.setBackground(new java.awt.Color(210, 6, 7));

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoMinimizarLayout = new javax.swing.GroupLayout(botaoMinimizar);
        botaoMinimizar.setLayout(botaoMinimizarLayout);
        botaoMinimizarLayout.setHorizontalGroup(
            botaoMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botaoMinimizarLayout.setVerticalGroup(
            botaoMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        blocoMain.add(botaoMinimizar);
        botaoMinimizar.setBounds(424, 0, 38, 45);

        botaoFechar.setBackground(new java.awt.Color(210, 6, 7));

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoFecharLayout = new javax.swing.GroupLayout(botaoFechar);
        botaoFechar.setLayout(botaoFecharLayout);
        botaoFecharLayout.setHorizontalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoFecharLayout.createSequentialGroup()
                .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoFecharLayout.setVerticalGroup(
            botaoFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        blocoMain.add(botaoFechar);
        botaoFechar.setBounds(462, 0, 38, 45);

        labelAsk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAsk.setForeground(new java.awt.Color(255, 255, 255));
        labelAsk.setText("Deseja sair?");
        blocoMain.add(labelAsk);
        labelAsk.setBounds(200, 70, 110, 22);

        painelSim.setBackground(new java.awt.Color(210, 6, 7));
        painelSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelSimMouseClicked(evt);
            }
        });

        sim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sim.setForeground(new java.awt.Color(255, 255, 255));
        sim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sim.setText("Sim");
        sim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelSimLayout = new javax.swing.GroupLayout(painelSim);
        painelSim.setLayout(painelSimLayout);
        painelSimLayout.setHorizontalGroup(
            painelSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(painelSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sim, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        painelSimLayout.setVerticalGroup(
            painelSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(painelSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sim, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        blocoMain.add(painelSim);
        painelSim.setBounds(120, 140, 120, 50);

        painelNao.setBackground(new java.awt.Color(210, 6, 7));
        painelNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelNaoMouseClicked(evt);
            }
        });

        nao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nao.setForeground(new java.awt.Color(255, 255, 255));
        nao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nao.setText("Não");
        nao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                naoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                naoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelNaoLayout = new javax.swing.GroupLayout(painelNao);
        painelNao.setLayout(painelNaoLayout);
        painelNaoLayout.setHorizontalGroup(
            painelNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(painelNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nao, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        painelNaoLayout.setVerticalGroup(
            painelNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(painelNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        blocoMain.add(painelNao);
        painelNao.setBounds(260, 140, 120, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blocoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(500, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        botaoMinimizar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        botaoMinimizar.setBackground(new Color(210,6,7));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        botaoFechar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        botaoFechar.setBackground(new Color(210,6,7));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void simMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simMouseClicked
        System.exit(0);
    }//GEN-LAST:event_simMouseClicked

    private void simMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simMouseEntered
        painelSim.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_simMouseEntered

    private void simMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simMouseExited
        painelSim.setBackground(new Color(210, 6, 7));
    }//GEN-LAST:event_simMouseExited

    private void painelSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelSimMouseClicked

    }//GEN-LAST:event_painelSimMouseClicked

    private void naoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naoMouseClicked
        dispose();
    }//GEN-LAST:event_naoMouseClicked

    private void naoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naoMouseEntered
        painelNao.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_naoMouseEntered

    private void naoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naoMouseExited
        painelNao.setBackground(new Color(210, 6, 7));
    }//GEN-LAST:event_naoMouseExited

    private void painelNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelNaoMouseClicked
    }//GEN-LAST:event_painelNaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraFerramentas;
    private javax.swing.JPanel blocoMain;
    private javax.swing.JPanel botaoFechar;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JPanel botaoMinimizar;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JLabel labelAsk;
    private javax.swing.JLabel nao;
    private javax.swing.JPanel painelNao;
    private javax.swing.JPanel painelSim;
    private javax.swing.JLabel sim;
    private javax.swing.JLabel telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
