/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forummtp;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author elton
 */
public class VisualizarTopico extends javax.swing.JFrame {

     protected Usuario recall = Home.user;
     protected static ArrayList <Topico> listaTopic = ForumMTP.listaTopicos;
     
    public void preencheBox(){
        for(int i = 0; i<listaTopic.size(); i++){
            caixaSelecao1.addItem(listaTopic.get(i).getTitulo());
        }
    }
    
    public void esvaziaBox(){
        caixaSelecao1.removeAllItems();
    }
    
    public void adicionarResp(Resposta res){
        Topico t=ForumMTP.listaTopicos.get(0);
        
        System.out.println("");
        System.out.println(tituloTopico.getText() + "\n");
        
        for(int i = 0; i<ForumMTP.listaTopicos.size(); i++){
            if(tituloTopico.getText().equals(ForumMTP.listaTopicos.get(i).getTitulo())){
                t = ForumMTP.listaTopicos.get(i);
                t.addResp(res);
            }
        }
        
        System.out.println(t + "\n");
        
        for(int i = 0; i<ForumMTP.listaTopicos.size(); i++){
            if(ForumMTP.listaTopicos.get(i).getTitulo().equals(t.getTitulo())){
                Gerenciadores.RemovedorTopico(ForumMTP.listaTopicos.get(i));
            }
        }
        
        ForumMTP.listaTopicos.add(t);
        
        for(int i = 0; i<ForumMTP.listaTopicos.size();i++){
            System.out.println(ForumMTP.listaTopicos.get(i));
        }
        
        Gerenciadores.escreverArquivoTopicosFalse(t);
        
        for(int i = 0; i<ForumMTP.listaTopicos.size(); i++){
            if(!ForumMTP.listaTopicos.get(i).getTitulo().equals(t.getTitulo())){
                Gerenciadores.escreverArquivoTopicos(ForumMTP.listaTopicos.get(i));
            }
        }
        
    }
    
    /**
     * Creates new form VisualizarTopico
     */
    public VisualizarTopico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        telaPrincipal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botaoMinimizarTelaP = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botaoFecharTelaP = new javax.swing.JLabel();
        caixaSelecao1 = new javax.swing.JComboBox<>();
        botaoBack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloTopico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        cont = new javax.swing.JScrollPane();
        conteudo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        painelBotaoProcurar = new javax.swing.JPanel();
        botaoProcurar = new javax.swing.JLabel();
        scrollResposta = new javax.swing.JScrollPane();
        areaResposta = new javax.swing.JTextArea();
        painelEnviar = new javax.swing.JPanel();
        botaoEnviarResp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(17, 17, 17));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        telaPrincipal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        telaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        telaPrincipal.setText("Visualizar Tópico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(988, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1124, 45);

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        botaoMinimizarTelaP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        botaoMinimizarTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoMinimizarTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoMinimizarTelaP.setText("-");
        botaoMinimizarTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMinimizarTelaP.setMaximumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setMinimumSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.setPreferredSize(new java.awt.Dimension(11, 43));
        botaoMinimizarTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMinimizarTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMinimizarTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1124, 0, 38, 45);

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));

        botaoFecharTelaP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoFecharTelaP.setForeground(new java.awt.Color(255, 255, 255));
        botaoFecharTelaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoFecharTelaP.setText("X");
        botaoFecharTelaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFecharTelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharTelaPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoFecharTelaP, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(1162, 0, 38, 45);

        caixaSelecao1.setToolTipText("");
        caixaSelecao1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caixaSelecao1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caixaSelecao1FocusLost(evt);
            }
        });
        caixaSelecao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaSelecao1MouseClicked(evt);
            }
        });
        caixaSelecao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSelecao1ActionPerformed(evt);
            }
        });
        jPanel1.add(caixaSelecao1);
        caixaSelecao1.setBounds(890, 60, 290, 20);

        botaoBack.setBackground(new java.awt.Color(255, 51, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forummtp/arrow.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout botaoBackLayout = new javax.swing.GroupLayout(botaoBack);
        botaoBack.setLayout(botaoBackLayout);
        botaoBackLayout.setHorizontalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botaoBackLayout.setVerticalGroup(
            botaoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(botaoBack);
        botaoBack.setBounds(20, 480, 100, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escolha o tópico:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 60, 110, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Conteúdo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 120, 90, 22);

        tituloTopico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloTopico.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tituloTopico);
        tituloTopico.setBounds(390, 80, 320, 20);

        jScrollPane1.setBackground(new java.awt.Color(17, 17, 17));
        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);

        jPanel5.setBackground(new java.awt.Color(17, 17, 17));

        cont.setBackground(new java.awt.Color(17, 17, 17));
        cont.setBorder(null);

        conteudo.setEditable(false);
        conteudo.setBackground(new java.awt.Color(17, 17, 17));
        conteudo.setColumns(20);
        conteudo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        conteudo.setForeground(new java.awt.Color(255, 255, 255));
        conteudo.setLineWrap(true);
        conteudo.setRows(5);
        conteudo.setBorder(null);
        conteudo.setPreferredSize(new java.awt.Dimension(740, 100));
        cont.setViewportView(conteudo);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cont, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 160, 800, 100);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Título do Tópico:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 80, 150, 22);

        painelBotaoProcurar.setBackground(new java.awt.Color(255, 51, 0));
        painelBotaoProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelBotaoProcurarMouseClicked(evt);
            }
        });

        botaoProcurar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoProcurar.setForeground(new java.awt.Color(255, 255, 255));
        botaoProcurar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoProcurar.setText("Procurar");
        botaoProcurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoProcurarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoProcurarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoProcurarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelBotaoProcurarLayout = new javax.swing.GroupLayout(painelBotaoProcurar);
        painelBotaoProcurar.setLayout(painelBotaoProcurarLayout);
        painelBotaoProcurarLayout.setHorizontalGroup(
            painelBotaoProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        painelBotaoProcurarLayout.setVerticalGroup(
            painelBotaoProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoProcurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(painelBotaoProcurar);
        painelBotaoProcurar.setBounds(1000, 90, 120, 30);

        areaResposta.setBackground(new java.awt.Color(35, 35, 35));
        areaResposta.setColumns(20);
        areaResposta.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        areaResposta.setForeground(new java.awt.Color(255, 255, 255));
        areaResposta.setRows(5);
        areaResposta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 88, 88), 2));
        areaResposta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaRespostaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaRespostaFocusLost(evt);
            }
        });
        scrollResposta.setViewportView(areaResposta);

        jPanel1.add(scrollResposta);
        scrollResposta.setBounds(250, 280, 490, 230);

        painelEnviar.setBackground(new java.awt.Color(255, 51, 0));
        painelEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelEnviarMouseClicked(evt);
            }
        });

        botaoEnviarResp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEnviarResp.setForeground(new java.awt.Color(255, 255, 255));
        botaoEnviarResp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoEnviarResp.setText("Enviar Resposta");
        botaoEnviarResp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEnviarResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEnviarRespMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEnviarRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEnviarRespMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelEnviarLayout = new javax.swing.GroupLayout(painelEnviar);
        painelEnviar.setLayout(painelEnviarLayout);
        painelEnviarLayout.setHorizontalGroup(
            painelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(painelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoEnviarResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEnviarLayout.setVerticalGroup(
            painelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(painelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoEnviarResp, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jPanel1.add(painelEnviar);
        painelEnviar.setBounds(425, 530, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMinimizarTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botaoMinimizarTelaPMouseClicked

    private void botaoMinimizarTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseEntered
        jPanel3.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseEntered

    private void botaoMinimizarTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMinimizarTelaPMouseExited
        jPanel3.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoMinimizarTelaPMouseExited

    private void botaoFecharTelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseClicked
        dispose();
    }//GEN-LAST:event_botaoFecharTelaPMouseClicked

    private void botaoFecharTelaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseEntered
        jPanel4.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_botaoFecharTelaPMouseEntered

    private void botaoFecharTelaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharTelaPMouseExited
        jPanel4.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_botaoFecharTelaPMouseExited

    private void caixaSelecao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSelecao1ActionPerformed
        
    }//GEN-LAST:event_caixaSelecao1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        botaoBack.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        botaoBack.setBackground(new Color(251, 51, 0));
    }//GEN-LAST:event_jLabel4MouseExited

    private void caixaSelecao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaSelecao1MouseClicked
    }//GEN-LAST:event_caixaSelecao1MouseClicked

    private void botaoProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProcurarMouseClicked
       Object nomeT = caixaSelecao1.getSelectedItem();
       
       try {
        Scanner scanner = new Scanner(new File("Topicos.txt")); //lê arquivo externo
        while (scanner.hasNext()) {
            try {
                String linha = (scanner.nextLine());
                String[] vetor = linha.split("/");
                
                Topico t = new Topico(vetor[0], vetor[1], vetor[2], vetor[3], vetor[4], vetor[5], vetor[6]);
                
                if(nomeT.equals(vetor[0])){
                    tituloTopico.setText(vetor[0]);
                    conteudo.setText(vetor[1]);
                }
            }
            catch (NoSuchElementException excecaoElemento)  { //trata erro
                System.err.println("Arquivo com formato incorreto");
                scanner.close();
                System.exit(1);
                }
            
            }
        
        } catch (FileNotFoundException e) { //trata erro
        System.err.println("Arquivo não encontrado");
        }
       
       
    }//GEN-LAST:event_botaoProcurarMouseClicked

    private void botaoProcurarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProcurarMouseEntered
        painelBotaoProcurar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoProcurarMouseEntered

    private void botaoProcurarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProcurarMouseExited
        painelBotaoProcurar.setBackground(new Color(255, 51, 00));
    }//GEN-LAST:event_botaoProcurarMouseExited

    private void painelBotaoProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBotaoProcurarMouseClicked

    }//GEN-LAST:event_painelBotaoProcurarMouseClicked

    private void caixaSelecao1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecao1FocusGained
        preencheBox();
    }//GEN-LAST:event_caixaSelecao1FocusGained

    private void caixaSelecao1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecao1FocusLost
        esvaziaBox();
    }//GEN-LAST:event_caixaSelecao1FocusLost

    private void areaRespostaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaRespostaFocusGained
        areaResposta.setBorder(new LineBorder(new Color(255,51,0), 2));
    }//GEN-LAST:event_areaRespostaFocusGained

    private void areaRespostaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaRespostaFocusLost
        areaResposta.setBorder(new LineBorder(new Color(88,88,88), 2));
    }//GEN-LAST:event_areaRespostaFocusLost

    private void botaoEnviarRespMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEnviarRespMouseClicked
        Resposta res = new Resposta(areaResposta.getText() + "#");
        
        // cria o tópico que terá a resposta adicionada
//        try {
//        Scanner scanner = new Scanner(new File("Topicos.txt")); //lê arquivo externo
//        while (scanner.hasNext()) {
//            try {
//                String linha = (scanner.nextLine());
//                String[] vetor = linha.split("/");
//                
//                if(tituloTopico.equals(vetor[0])){
//                    t = new Topico(vetor[0], vetor[1], vetor[2], vetor[3], vetor[4], vetor[5], vetor[6]);
//                    t.addResp(areaText);
//                }
//            }
//            catch (NoSuchElementException excecaoElemento)  { //trata erro
//                System.err.println("Arquivo com formato incorreto");
//                scanner.close();
//                System.exit(1);
//                }
//            }
//        } catch (FileNotFoundException e) { //trata erro
//        System.err.println("Arquivo não encontrado");
//        }
//        
//        for(int i = 0; i<ForumMTP.listaTopicos.size(); i++){
//            if(ForumMTP.listaTopicos.get(i).getTitulo().equals(t.getTitulo())){
//                ForumMTP.RemovedorTopico(ForumMTP.listaTopicos.get(i));
//            }
//        }
//        
//        ForumMTP.listaTopicos.add(t);
//    
//        ForumMTP.escreverArquivoTopicosFalse(t);
//        
//        for(int i = 0 ; i<ForumMTP.listaTopicos.size(); i++){
//            if(!ForumMTP.listaTopicos.get(i).getTitulo().equals(t.getTitulo())){
//                ForumMTP.escreverArquivoTopicos(ForumMTP.listaTopicos.get(i));
//         }
//        }
        
        adicionarResp(res);

        recall.ContadorRespostas();
        
        for(int i = 0; i<ForumMTP.listaUsuarios.size(); i++){
            if(ForumMTP.listaUsuarios.get(i).getUser().equals(recall.getUser())){
                Gerenciadores.RemovedorUser(ForumMTP.listaUsuarios.get(i));
            }
        }
        
        ForumMTP.listaUsuarios.add(recall);
        
        for(int i = 0; i<ForumMTP.listaUsuarios.size(); i++)
        System.out.println(ForumMTP.listaUsuarios.get(i)); //vê o q está acontecendo
        
        System.out.println("");
        
        Gerenciadores.escreverArquivoUsuariosFalse(recall);
        
        for(int i = 0 ; i<ForumMTP.listaUsuarios.size(); i++){
            if(!ForumMTP.listaUsuarios.get(i).getUser().equals(recall.getUser())){
                Gerenciadores.escreverArquivoUsuarios(ForumMTP.listaUsuarios.get(i));
         }
        }
        
        new Home().setVisible(true);
        Home.mudaTexto(recall.getUser());
        dispose();
    }//GEN-LAST:event_botaoEnviarRespMouseClicked

    private void botaoEnviarRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEnviarRespMouseEntered
        painelEnviar.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botaoEnviarRespMouseEntered

    private void botaoEnviarRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEnviarRespMouseExited
        painelEnviar.setBackground(new Color(255, 51, 00));
    }//GEN-LAST:event_botaoEnviarRespMouseExited

    private void painelEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelEnviarMouseClicked

    }//GEN-LAST:event_painelEnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarTopico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarTopico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResposta;
    private javax.swing.JPanel botaoBack;
    private javax.swing.JLabel botaoEnviarResp;
    private javax.swing.JLabel botaoFecharTelaP;
    private javax.swing.JLabel botaoMinimizarTelaP;
    private javax.swing.JLabel botaoProcurar;
    protected static javax.swing.JComboBox<String> caixaSelecao1;
    private javax.swing.JScrollPane cont;
    private javax.swing.JTextArea conteudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelBotaoProcurar;
    private javax.swing.JPanel painelEnviar;
    private javax.swing.JScrollPane scrollResposta;
    private javax.swing.JLabel telaPrincipal;
    private javax.swing.JLabel tituloTopico;
    // End of variables declaration//GEN-END:variables
}
